### ISSUE TITLE
Tìm hiểu về Git

### ISSUE THREAD

**Issue by LongCaoBK** [LongCaoBK/thanhvd-training#1]
Thành tìm hiểu Git theo các tiêu chí bên dưới nhé, sau đó viết lại tài liệu và push lên repo này.

##### 1. Những khái niệm chung
- Git là gì?
- Git repository là gì?
- Git & Github & Gitlab giống/khác gì nhau?
- Các trạng thái có thể có trong git repository

##### 2. Config cho git với git config
- Config thông tin cá nhân
- Config default/prefered editor
- Config global .gitignore
 
##### 3. Các thao tác ban đầu
- Khởi tạo repo với git init
 
##### 4. Git commit
- Commit trong git là gì
- Một commit chứa những thông tin gì
- Amending - Thay Đổi Commit Cuối Cùng
 
##### 5. Làm việc với branch
- Tạo mới branch
- Nhảy từ branch này sang branch khác
- Đổi tên branch
 
##### 7. Các thao tác liên quan khác
- Git Merge
- Git Rebase
- Git Rebase interactive
- Git Rebase khi remote có cập nhật mới
- Git Cherry-pick
- Git Pull
- Git Push
- Tùy chọn force
- Git reset
 
##### 8. Các thao tác với git remote
- Add remote
- Rename remote
- Update remote
- Prune remote branch
 
##### 9. Các thao tác với Stash
- Tổng quan về git stash
- git stash list
- git stash clear

**Comment by LongCaoBK** [comment]
@vuducthanh0115 duedate là 16/07/2021.

Trong quá trình làm có gì thắc mắc tích cực comment lên issue, để anh biết và có thể trả lời.

**Comment by LongCaoBK** [comment]
@vuducthanh0115 chú biết dùng Linux OS chưa nhỉ?

**Comment by thanhvd1501** [comment]
> @vuducthanh0115 chú biết dùng Linux OS chưa nhỉ?

em chưa ạ

**Comment by LongCaoBK** [comment]
> > @vuducthanh0115 chú biết dùng Linux OS chưa nhỉ?
> 
> em chưa ạ

Ok em

**Comment by LongCaoBK** [comment]
@vuducthanh0115 

**Chú ý**: đến 4h chiều các ngày làm việc thì 
- Comment cập nhật tiến độ công việc đã làm trong ngày 
- Push phần việc đã làm lên git repo

**Comment by thanhvd1501** [comment]
Em xin phép báo cáo công việc anh đã phân công ạ .
Em tìm hiểu và học những nội dung trên tuy nhiên còn 1 vài nội dung khá là mới em vẫn đang đọc chưa xong đó là 
Git Rebase interactive, Git Rebase khi remote có cập nhật mới, Git Cherry-pick, Tùy chọn force, Update remote, Prune remote branch
Em sẽ hoàn thành nốt những nội dung trên vào ngày mai ạ.

**Comment by thanhvd1501** [comment]
Anh ơi em nộp nội dung báo cáo bằng link docs hay là push trực tiếp file trong máy lên git repo ạ

**Comment by thanhvd1501** [comment]
Em đã up 1 file lên git repo ạ còn đây là link docs ạ 
https://docs.google.com/document/d/1qFi8K8UF-jExQcZGXD0PHT3Vbla9IpMKR8-bXLtfiaY/edit?usp=sharing

**Comment by LongCaoBK** [comment]
> Em xin phép báo cáo công việc anh đã phân công ạ .
> Em tìm hiểu và học những nội dung trên tuy nhiên còn 1 vài nội dung khá là mới em vẫn đang đọc chưa xong đó là
> Git Rebase interactive, Git Rebase khi remote có cập nhật mới, Git Cherry-pick, Tùy chọn force, Update remote, Prune remote branch
> Em sẽ hoàn thành nốt những nội dung trên vào ngày mai ạ.

Ok chú

**Comment by LongCaoBK** [comment]
> Anh ơi em nộp nội dung báo cáo bằng link docs hay là push trực tiếp file trong máy lên git repo ạ

- Các nội dung trong issue em đều đẩy lên repo.
- Em viết lại tài liệu dưới format markdown rồi push lên repo (Ref: [cách viết tài liệu markdown](https://guides.github.com/features/mastering-markdown/)), & tạo một folder riêng cho issue tìm hiểu git này.

**Comment by thanhvd1501** [comment]
> > Anh ơi em nộp nội dung báo cáo bằng link docs hay là push trực tiếp file trong máy lên git repo ạ
> 
> * Các nội dung trong issue em đều đẩy lên repo.
> * Em viết lại tài liệu dưới format markdown rồi push lên repo (Ref: [cách viết tài liệu markdown](https://guides.github.com/features/mastering-markdown/)), & tạo một folder riêng cho issue tìm hiểu git này.

Vâng ạ để em làm lại ạ

**Comment by thanhvd1501** [comment]
Em xin báo cáo tình hình tìm hiểu hôm nay ạ.
Em đã tìm hiểu toàn bộ nội dung về git như yêu cầu anh đã đưa ra ạ và em đã tổng hợp lại theo ý hiểu của em ở file [git](https://github.com/LongCaoBK/thanhvd-training/blob/main/Learn%20about%20GIT/GIT.md) ạ. 
Anh check giúp em xem có gì sai sót để em tìm hiểu và cập nhật lại ạ.
Em cảm ơn ạ.

**Comment by LongCaoBK** [comment]
> Em xin báo cáo tình hình tìm hiểu hôm nay ạ.
> Em đã tìm hiểu toàn bộ nội dung về git như yêu cầu anh đã đưa ra ạ và em đã tổng hợp lại theo ý hiểu của em ở file [git](https://github.com/LongCaoBK/thanhvd-training/blob/main/Learn%20about%20GIT/GIT.md) ạ.
> Anh check giúp em xem có gì sai sót để em tìm hiểu và cập nhật lại ạ.
> Em cảm ơn ạ.

Ok nhé

**Comment by LongCaoBK** [comment]
@vuducthanh0115 em tạo branch mới, push phần đã làm lên, sau đó tạo merge request để anh review trực tiếp nhé.

**Comment by LongCaoBK** [comment]
Đã merge PR: https://github.com/LongCaoBK/thanhvd-training/pull/2
