### ISSUE TITLE
Tổng quan Linux

### ISSUE THREAD

**Issue by LongCaoBK** [LongCaoBK/thanhvd-training#3]
@vuducthanh0115 issue tiep theo nhe, tao Pull Request tuong tu issue dau tien.

# Tổng quan Linux

- [ ] Tổng quan

  - [ ] Kiến trúc
  - [ ] Thành phần
    - [ ] Kernel
    - [ ] Shell
    - [ ] Commands and Utilities
    - [ ] Files and Directories
  - [ ] Quản lý thư mục
  - [ ] Quản lý tập tin
  - [ ] Vim & Nano Editor
  - [ ] Các biến môi trường
  - [ ] Quản lý tiến trình
  - [ ] Truyền thông giữa các máy

- [ ] Lập trình Bash Shell
  - [ ] Khái niệm
  - [ ] Biến
    - [ ] Local Variables
    - [ ] Environment Variables
    - [ ] Shell Variables
    - [ ] Special Variables
  - [ ] Toán tử và toán hạng
  - [ ] Câu lệnh điều khiển
    - [ ] if...else
    - [ ] case...esac
    - [ ] loop
      - [ ] while
      - [ ] for
      - [ ] until
      - [ ] select
  - [ ] Hàm

**Comment by thanhvd1501** [comment]
Em xin báo cáo tình hình tìm hiểu ạ.
Em đang tìm hiểu phần đầu tiên là tổng quan và còn 3 nội dung nhỏ nữa là : Các biến môi trường, Quản lý tiến trình, Truyền thông giữa các máy em đang tìm hiểu chưa xong ạ.
Em xin phép hoàn thành nốt 3 nội dung đó và phần lập trình Bash Shell vào ngày mai ạ.

**Comment by thanhvd1501** [comment]
@LongCaoBK Em đã ghi lại các nội dung tìm hiểu được em có cần push lên git repo và tạo 1 pull request ko ạ hay để hoàn thành tất cả thì push ạ

**Comment by LongCaoBK** [comment]
> @LongCaoBK Em đã ghi lại các nội dung tìm hiểu được em có cần push lên git repo và tạo 1 pull request ko ạ hay để hoàn thành tất cả thì push ạ

Push len di em

**Comment by thanhvd1501** [comment]
> > @LongCaoBK Em đã ghi lại các nội dung tìm hiểu được em có cần push lên git repo và tạo 1 pull request ko ạ hay để hoàn thành tất cả thì push ạ
> 
> Push len di em

Vâng em vừa push rồi ạ

**Comment by thanhvd1501** [comment]
Em xin phép báo cáo tình hình tìm hiểu ngày hôm nay ạ.  
Em đã tìm hiểu hết các nội dung yêu cầu, đã tổng hợp lại và update lại pull request rồi ạ.  
Anh check giúp em xem có sai sót gì không ạ.  
Về phần tổng quan Linux có khá nhiều lệnh mới em chưa nhớ hết được và em sẽ tiếp tục thực hành ạ.  
Còn phần lập trình Bash Shell thì khá giống với ngôn ngữ lập trình em đã được học ạ nên phần này không có gì.

**Comment by LongCaoBK** [comment]
> Em xin phép báo cáo tình hình tìm hiểu ngày hôm nay ạ.
> Em đã tìm hiểu hết các nội dung yêu cầu, đã tổng hợp lại và update lại pull request rồi ạ.
> Anh check giúp em xem có sai sót gì không ạ.
> Về phần tổng quan Linux có khá nhiều lệnh mới em chưa nhớ hết được và em sẽ tiếp tục thực hành ạ.
> Còn phần lập trình Bash Shell thì khá giống với ngôn ngữ lập trình em đã được học ạ nên phần này không có gì.

Lần sau chú ý cách đặt tên branch và tên pull request nhé, để tên có ý nghĩa và liên quan đến issue chú đang làm.

VD: 
- Branch: linux_document
- Tên Pull Request: Tài liệu tổng quan về linux

**Comment by thanhvd1501** [comment]
> > Em xin phép báo cáo tình hình tìm hiểu ngày hôm nay ạ.
> > Em đã tìm hiểu hết các nội dung yêu cầu, đã tổng hợp lại và update lại pull request rồi ạ.
> > Anh check giúp em xem có sai sót gì không ạ.
> > Về phần tổng quan Linux có khá nhiều lệnh mới em chưa nhớ hết được và em sẽ tiếp tục thực hành ạ.
> > Còn phần lập trình Bash Shell thì khá giống với ngôn ngữ lập trình em đã được học ạ nên phần này không có gì.
> 
> Lần sau chú ý cách đặt tên branch và tên pull request nhé, để tên có ý nghĩa và liên quan đến issue chú đang làm.
> 
> VD:
> 
> * Branch: linux_document
> * Tên Pull Request: Tài liệu tổng quan về linux

Ok ạ

**Comment by thanhvd1501** [comment]
Em xin báo cáo tình hình tìm hiểu ngày hôm nay ạ.
Em đã tìm hiểu theo những nội dung anh yêu cầu thêm về docker và em đã update lại tài liệu rồi ạ
